[package]
name = "bevy_collider_gen"
# don't manually edit this version unless you're sure you want to circumvent the process documented in RELEASE.md
version = "0.2.2"
edition = "2021"
homepage = "https://github.com/shnewto/bevy_collider_gen"
license = "MIT OR Apache-2.0"
repository = "https://github.com/shnewto/bevy_collider_gen"

description = "a library for generating colliders, for bevy apps, from images with transparency"
keywords = ["bevy", "rapier", "png", "collider", "2d"]
readme = "README.md"

[lints.clippy]
cast_precision_loss = { level = "allow", priority = 1 }
pedantic = { level = "warn", priority = 0 }

[features]
default = ["rapier2d", "parallel"]
avian2d = ["dep:avian2d"]
rapier2d = ["dep:bevy_rapier2d"]
parallel = ["dep:rayon", "avian2d/parallel", "bevy_rapier2d/parallel"]

[dependencies]
edges = "0.4"
bevy_math = { version = "0.14", default-features = false }
rayon = { version = "1", optional = true }

[dependencies.bevy_rapier2d]
version = "0.27"
optional = true
default-features = false
features = ["dim2", "headless"]

[dependencies.avian2d]
version = "0.1"
optional = true
default-features = false
features = ["2d", "parry-f32"]

[dev-dependencies]
bevy = "0.14"
bevy_prototype_lyon = "0.12"
indoc = "2.0.4"

[[example]]
name = "avian2d_colliders"
path = "examples/avian2d_colliders.rs"
required-features = ["avian2d", "avian2d/debug-plugin"]

[[example]]
name = "rapier2d_colliders"
path = "examples/rapier2d_colliders.rs"
required-features = ["rapier2d", "bevy_rapier2d/debug-render-2d"]
