[package]
name = "bevy_collider_gen"
# don't manually edit this version unless you're sure you want to circumvent the process documented in RELEASE.md
version = "0.2.2"
edition = "2021"
homepage = "https://github.com/shnewto/bevy_collider_gen"
license = "MIT OR Apache-2.0"
repository = "https://github.com/shnewto/bevy_collider_gen"

description = "a library for generating colliders, for bevy apps, from images with transparency"
keywords = ["bevy", "rapier", "png", "collider", "2d"]
readme = "README.md"

[lints.clippy]
cast_precision_loss = { level = "allow", priority = 1 }
pedantic = { level = "warn", priority = 0 }

[features]
default = ["avian2d", "rapier2d"]
avian2d = ["dep:avian2d"]
rapier2d = ["dep:bevy_rapier2d"]

[dependencies]
rayon = "1.10.0"
bevy_rapier2d = { version = "0.27.0", optional = true }
avian2d = { version = "0.1.0", optional = true }
edges = { version = "0.3.4", features = ["bevy"] }
thiserror = "2.0.3"

[dependencies.bevy_math]
version = "0.14"
default-features = false

[dependencies.bevy_render]
version = "0.14"
default-features = false

[dev-dependencies]
bevy = "0.14"
bevy_prototype_lyon = "0.12.0"
indoc = "2.0.4"

[[example]]
name = "avian2d_colliders"
path = "examples/avian2d_colliders.rs"
required-features = ["avian2d"]

[[example]]
name = "rapier2d_colliders"
path = "examples/rapier2d_colliders.rs"
required-features = ["rapier2d"]
