[package]
name = "bevy_collider_gen"
# don't manually edit this version unless you're sure you want to circumvent the process documented in RELEASE.md
version = "0.2.1"
edition = "2021"
homepage = "https://github.com/shnewto/bevy_collider_gen"
license = "MIT OR Apache-2.0"
repository = "https://github.com/shnewto/bevy_collider_gen"

description = "a library for generating colliders, for bevy apps, from images with transparency"
keywords = ["bevy", "rapier", "png", "collider", "2d"]
readme = "README.md"

[features]
default = ["xpbd_2d", "rapier2d"]
xpbd_2d = ["dep:bevy_xpbd_2d"]
rapier2d = ["dep:bevy_rapier2d"]

[dependencies]
bevy = "0.13.0"
bevy_rapier2d = { version = "0.25.0", optional = true }
bevy_xpbd_2d = { version = "0.4.2", optional = true }
edges = { version = "0.3.2", features = ["bevy"] }
thiserror = "1.0.57"

[dev-dependencies]
bevy_prototype_lyon = "0.11.0"
indoc = "2.0.4"

[[example]]
name = "xpbd_2d_colliders"
path = "examples/xpbd_2d_colliders.rs"
required-features = ["xpbd_2d"]

[[example]]
name = "rapier2d_colliders"
path = "examples/rapier2d_colliders.rs"
required-features = ["rapier2d"]
